export interface Product {
  id: number
  name: string
  description: string
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  category: string
  location: string
  colors?: string[]
  inStock: number
  brand: string
}

export const products: Product[] = [
  // Electronics - Headphones
  {
    id: 1,
    name: "Wireless Earbuds, IPX8",
    description: "Organic Cotton, fairtrade certified",
    price: 89,
    rating: 4.5,
    reviews: 121,
    image: "/black-wireless-earbuds.jpg",
    category: "Electronics",
    location: "New York",
    colors: ["black", "white"],
    inStock: 15,
    brand: "TechSound",
  },
  {
    id: 2,
    name: "AirPods Max",
    description: "A perfect balance of high-fidelity audio",
    price: 559,
    rating: 4.8,
    reviews: 134,
    image: "/pink-airpods-max-headphones.jpg",
    category: "Electronics",
    location: "California",
    colors: ["pink", "black", "silver", "blue", "green"],
    inStock: 12,
    brand: "Apple",
  },
  {
    id: 3,
    name: "Bose BT Earphones",
    description: "Premium noise cancelling technology",
    price: 289,
    rating: 4.6,
    reviews: 267,
    image: "/black-over-ear-headphones.jpg",
    category: "Electronics",
    location: "Texas",
    colors: ["black", "silver"],
    inStock: 8,
    brand: "Bose",
  },
  {
    id: 4,
    name: "VIVEFOX Headphones",
    description: "Wired Stereo Headset With Mic",
    price: 39,
    rating: 4.3,
    reviews: 167,
    image: "/red-wired-headphones.jpg",
    category: "Electronics",
    location: "Florida",
    colors: ["red", "black"],
    inStock: 25,
    brand: "VIVEFOX",
  },
  {
    id: 5,
    name: "JBL TUNE 500BT/NC",
    description: "Premium Bone Conduction Open Ear Bluetooth",
    price: 59,
    rating: 4.2,
    reviews: 123,
    image: "/black-over-ear-headphones-jbl.jpg",
    category: "Electronics",
    location: "New York",
    colors: ["black", "blue"],
    inStock: 18,
    brand: "JBL",
  },

  // Furniture
  {
    id: 6,
    name: "Modern Office Chair",
    description: "Ergonomic design with lumbar support",
    price: 299,
    rating: 4.4,
    reviews: 89,
    image: "/modern-office-chair.png",
    category: "Furniture",
    location: "California",
    colors: ["black", "gray", "white"],
    inStock: 12,
    brand: "ComfortSeating",
  },
  {
    id: 7,
    name: "Wooden Dining Table",
    description: "Solid oak wood, seats 6 people",
    price: 599,
    rating: 4.7,
    reviews: 156,
    image: "/wooden-dining-table.png",
    category: "Furniture",
    location: "Texas",
    colors: ["oak", "walnut", "cherry"],
    inStock: 5,
    brand: "WoodCraft",
  },
  {
    id: 8,
    name: "Leather Sofa Set",
    description: "3-piece genuine leather sofa set",
    price: 1299,
    rating: 4.6,
    reviews: 203,
    image: "/leather-sofa-set.png",
    category: "Furniture",
    location: "New York",
    colors: ["brown", "black", "cream"],
    inStock: 3,
    brand: "LuxuryHome",
  },
  {
    id: 9,
    name: "Standing Desk",
    description: "Height adjustable electric standing desk",
    price: 449,
    rating: 4.5,
    reviews: 178,
    image: "/standing-desk-setup.png",
    category: "Furniture",
    location: "Florida",
    colors: ["white", "black", "bamboo"],
    inStock: 9,
    brand: "ErgoDesk",
  },
  {
    id: 10,
    name: "Bookshelf Cabinet",
    description: "5-tier wooden bookshelf with storage",
    price: 189,
    rating: 4.3,
    reviews: 134,
    image: "/wooden-bookshelf.png",
    category: "Furniture",
    location: "California",
    colors: ["oak", "white", "black"],
    inStock: 14,
    brand: "StoragePlus",
  },

  // Shoes
  {
    id: 11,
    name: "Running Sneakers",
    description: "Lightweight breathable running shoes",
    price: 129,
    rating: 4.4,
    reviews: 245,
    image: "/running-sneakers.png",
    category: "Shoes",
    location: "New York",
    colors: ["white", "black", "blue", "red"],
    inStock: 22,
    brand: "SportMax",
  },
  {
    id: 12,
    name: "Leather Boots",
    description: "Waterproof leather hiking boots",
    price: 199,
    rating: 4.6,
    reviews: 167,
    image: "/leather-hiking-boots.jpg",
    category: "Shoes",
    location: "Texas",
    colors: ["brown", "black"],
    inStock: 16,
    brand: "OutdoorGear",
  },
  {
    id: 13,
    name: "Canvas Sneakers",
    description: "Classic canvas low-top sneakers",
    price: 79,
    rating: 4.2,
    reviews: 189,
    image: "/canvas-sneakers.png",
    category: "Shoes",
    location: "California",
    colors: ["white", "black", "red", "navy"],
    inStock: 28,
    brand: "ClassicWear",
  },
  {
    id: 14,
    name: "Formal Dress Shoes",
    description: "Oxford style leather dress shoes",
    price: 249,
    rating: 4.5,
    reviews: 123,
    image: "/formal-dress-shoes.jpg",
    category: "Shoes",
    location: "Florida",
    colors: ["black", "brown"],
    inStock: 11,
    brand: "FormalStyle",
  },
  {
    id: 15,
    name: "Athletic Trainers",
    description: "Cross-training athletic shoes",
    price: 159,
    rating: 4.3,
    reviews: 201,
    image: "/athletic-trainers.jpg",
    category: "Shoes",
    location: "New York",
    colors: ["white", "gray", "black"],
    inStock: 19,
    brand: "FitGear",
  },

  // Bags
  {
    id: 16,
    name: "Laptop Backpack",
    description: "Water-resistant laptop backpack with USB port",
    price: 89,
    rating: 4.4,
    reviews: 156,
    image: "/laptop-backpack.png",
    category: "Bags",
    location: "California",
    colors: ["black", "gray", "navy"],
    inStock: 24,
    brand: "TechBag",
  },
  {
    id: 17,
    name: "Leather Handbag",
    description: "Genuine leather designer handbag",
    price: 199,
    rating: 4.6,
    reviews: 134,
    image: "/leather-handbag.png",
    category: "Bags",
    location: "Texas",
    colors: ["black", "brown", "tan"],
    inStock: 13,
    brand: "LuxBags",
  },
  {
    id: 18,
    name: "Travel Duffel Bag",
    description: "Large capacity travel duffel with wheels",
    price: 149,
    rating: 4.3,
    reviews: 178,
    image: "/travel-duffel-bag.jpg",
    category: "Bags",
    location: "Florida",
    colors: ["black", "navy", "gray"],
    inStock: 17,
    brand: "TravelPro",
  },
  {
    id: 19,
    name: "Canvas Tote Bag",
    description: "Eco-friendly canvas tote bag",
    price: 39,
    rating: 4.1,
    reviews: 89,
    image: "/canvas-tote-bag.png",
    category: "Bags",
    location: "New York",
    colors: ["natural", "black", "navy"],
    inStock: 31,
    brand: "EcoBag",
  },
  {
    id: 20,
    name: "Crossbody Messenger",
    description: "Compact crossbody messenger bag",
    price: 79,
    rating: 4.2,
    reviews: 112,
    image: "/crossbody-messenger-bag.jpg",
    category: "Bags",
    location: "California",
    colors: ["black", "brown", "olive"],
    inStock: 21,
    brand: "UrbanCarry",
  },

  // Books
  {
    id: 21,
    name: "Programming Fundamentals",
    description: "Complete guide to programming basics",
    price: 49,
    rating: 4.7,
    reviews: 234,
    image: "/programming-book.png",
    category: "Books",
    location: "New York",
    colors: ["blue"],
    inStock: 45,
    brand: "TechBooks",
  },
  {
    id: 22,
    name: "Design Thinking",
    description: "Creative problem solving methodology",
    price: 39,
    rating: 4.5,
    reviews: 167,
    image: "/design-thinking-book.jpg",
    category: "Books",
    location: "California",
    colors: ["orange"],
    inStock: 38,
    brand: "CreativePress",
  },
  {
    id: 23,
    name: "Business Strategy",
    description: "Modern business strategy handbook",
    price: 59,
    rating: 4.4,
    reviews: 189,
    image: "/business-strategy-book.jpg",
    category: "Books",
    location: "Texas",
    colors: ["green"],
    inStock: 29,
    brand: "BusinessPub",
  },
  {
    id: 24,
    name: "Data Science Guide",
    description: "Comprehensive data science textbook",
    price: 69,
    rating: 4.6,
    reviews: 201,
    image: "/data-science-book.jpg",
    category: "Books",
    location: "Florida",
    colors: ["purple"],
    inStock: 33,
    brand: "DataPress",
  },
  {
    id: 25,
    name: "Photography Basics",
    description: "Learn photography from scratch",
    price: 44,
    rating: 4.3,
    reviews: 145,
    image: "/photography-book.jpg",
    category: "Books",
    location: "New York",
    colors: ["black"],
    inStock: 27,
    brand: "PhotoGuide",
  },
]

export const categories = ["All", "Electronics", "Furniture", "Shoes", "Bags", "Books"]
export const locations = ["All", "New York", "California", "Texas", "Florida"]
